"""Dodajemy plec

Revision ID: 217e231e1246
Revises: 
Create Date: 2026-02-09 18:21:41.760580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217e231e1246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
