"""usuwamy plec


Revision ID: 6a880f7e4725
Revises: 217e231e1246
Create Date: 2026-02-09 18:25:36.485619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a880f7e4725'
down_revision = '217e231e1246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
